line-length = 88

select = [
    "ALL",
    "C90",
    "I",
]

ignore = [
    "D203", # One blank line required before class docstring (conflicts with D211)
    "D213", # Multi-line docstring summary should start at the second line
    "D400", # First line should end with a period
    "D415", # First line should end with a period, question mark, or exclamation point
]

exclude = [
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "migrations",
    "static",
    "templates",
    "templates_old"
]
target-version = "py313"

[mccabe]
max-complexity = 8

[isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["your_project"]
