services:
  web:
    build: .
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/var/www/certbot
      - ./certs:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./webroot:/var/www/certbot
      - ./certs:/etc/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done'